package com.looker.notesy.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF676013)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF0E58B)
val onPrimaryContainerLight = Color(0xFF1F1C00)
val secondaryLight = Color(0xFF635F41)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEAE3BD)
val onSecondaryContainerLight = Color(0xFF1F1C05)
val tertiaryLight = Color(0xFF456731)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFC5EFAA)
val onTertiaryContainerLight = Color(0xFF082100)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEF9EB)
val onBackgroundLight = Color(0xFF1D1C14)
val surfaceLight = Color(0xFFFEF9EB)
val onSurfaceLight = Color(0xFF1D1C14)
val surfaceVariantLight = Color(0xFFE8E2D0)
val onSurfaceVariantLight = Color(0xFF49473A)
val outlineLight = Color(0xFF7A7768)
val outlineVariantLight = Color(0xFFCBC7B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323127)
val inverseOnSurfaceLight = Color(0xFFF6F0E3)
val inversePrimaryLight = Color(0xFFD3C972)
val surfaceDimLight = Color(0xFFDEDACC)
val surfaceBrightLight = Color(0xFFFEF9EB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F3E6)
val surfaceContainerLight = Color(0xFFF3EEE0)
val surfaceContainerHighLight = Color(0xFFEDE8DA)
val surfaceContainerHighestLight = Color(0xFFE7E2D5)

val primaryLightMediumContrast = Color(0xFF4A4400)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF7E7629)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF474428)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF7A7556)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF2A4B18)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF5A7E45)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF9EB)
val onBackgroundLightMediumContrast = Color(0xFF1D1C14)
val surfaceLightMediumContrast = Color(0xFFFEF9EB)
val onSurfaceLightMediumContrast = Color(0xFF1D1C14)
val surfaceVariantLightMediumContrast = Color(0xFFE8E2D0)
val onSurfaceVariantLightMediumContrast = Color(0xFF454336)
val outlineLightMediumContrast = Color(0xFF625F51)
val outlineVariantLightMediumContrast = Color(0xFF7E7B6C)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF323127)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF6F0E3)
val inversePrimaryLightMediumContrast = Color(0xFFD3C972)
val surfaceDimLightMediumContrast = Color(0xFFDEDACC)
val surfaceBrightLightMediumContrast = Color(0xFFFEF9EB)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F3E6)
val surfaceContainerLightMediumContrast = Color(0xFFF3EEE0)
val surfaceContainerHighLightMediumContrast = Color(0xFFEDE8DA)
val surfaceContainerHighestLightMediumContrast = Color(0xFFE7E2D5)

val primaryLightHighContrast = Color(0xFF262300)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF4A4400)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF25230A)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF474428)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF0B2800)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF2A4B18)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF9EB)
val onBackgroundLightHighContrast = Color(0xFF1D1C14)
val surfaceLightHighContrast = Color(0xFFFEF9EB)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE8E2D0)
val onSurfaceVariantLightHighContrast = Color(0xFF262419)
val outlineLightHighContrast = Color(0xFF454336)
val outlineVariantLightHighContrast = Color(0xFF454336)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF323127)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFFAEF93)
val surfaceDimLightHighContrast = Color(0xFFDEDACC)
val surfaceBrightLightHighContrast = Color(0xFFFEF9EB)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF8F3E6)
val surfaceContainerLightHighContrast = Color(0xFFF3EEE0)
val surfaceContainerHighLightHighContrast = Color(0xFFEDE8DA)
val surfaceContainerHighestLightHighContrast = Color(0xFFE7E2D5)

val primaryDark = Color(0xFFD3C972)
val onPrimaryDark = Color(0xFF363100)
val primaryContainerDark = Color(0xFF4E4800)
val onPrimaryContainerDark = Color(0xFFF0E58B)
val secondaryDark = Color(0xFFCDC7A3)
val onSecondaryDark = Color(0xFF343117)
val secondaryContainerDark = Color(0xFF4B472C)
val onSecondaryContainerDark = Color(0xFFEAE3BD)
val tertiaryDark = Color(0xFFAAD290)
val onTertiaryDark = Color(0xFF183807)
val tertiaryContainerDark = Color(0xFF2E4F1C)
val onTertiaryContainerDark = Color(0xFFC5EFAA)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF15140C)
val onBackgroundDark = Color(0xFFE7E2D5)
val surfaceDark = Color(0xFF15140C)
val onSurfaceDark = Color(0xFFE7E2D5)
val surfaceVariantDark = Color(0xFF49473A)
val onSurfaceVariantDark = Color(0xFFCBC7B5)
val outlineDark = Color(0xFF959181)
val outlineVariantDark = Color(0xFF49473A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E2D5)
val inverseOnSurfaceDark = Color(0xFF323127)
val inversePrimaryDark = Color(0xFF676013)
val surfaceDimDark = Color(0xFF15140C)
val surfaceBrightDark = Color(0xFF3B3930)
val surfaceContainerLowestDark = Color(0xFF0F0E07)
val surfaceContainerLowDark = Color(0xFF1D1C14)
val surfaceContainerDark = Color(0xFF212017)
val surfaceContainerHighDark = Color(0xFF2C2A21)
val surfaceContainerHighestDark = Color(0xFF37352C)

val primaryDarkMediumContrast = Color(0xFFD7CD76)
val onPrimaryDarkMediumContrast = Color(0xFF191700)
val primaryContainerDarkMediumContrast = Color(0xFF9B9342)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFD2CCA7)
val onSecondaryDarkMediumContrast = Color(0xFF191702)
val secondaryContainerDarkMediumContrast = Color(0xFF979270)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFAED694)
val onTertiaryDarkMediumContrast = Color(0xFF061B00)
val tertiaryContainerDarkMediumContrast = Color(0xFF769B5F)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF15140C)
val onBackgroundDarkMediumContrast = Color(0xFFE7E2D5)
val surfaceDarkMediumContrast = Color(0xFF15140C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFAF2)
val surfaceVariantDarkMediumContrast = Color(0xFF49473A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFCFCBB9)
val outlineDarkMediumContrast = Color(0xFFA7A392)
val outlineVariantDarkMediumContrast = Color(0xFF878374)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E2D5)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C2A21)
val inversePrimaryDarkMediumContrast = Color(0xFF4F4900)
val surfaceDimDarkMediumContrast = Color(0xFF15140C)
val surfaceBrightDarkMediumContrast = Color(0xFF3B3930)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF0F0E07)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1C14)
val surfaceContainerDarkMediumContrast = Color(0xFF212017)
val surfaceContainerHighDarkMediumContrast = Color(0xFF2C2A21)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF37352C)

val primaryDarkHighContrast = Color(0xFFFFFAF2)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD7CD76)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFFFFAF2)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFD2CCA7)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFF2FFE5)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFAED694)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF15140C)
val onBackgroundDarkHighContrast = Color(0xFFE7E2D5)
val surfaceDarkHighContrast = Color(0xFF15140C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49473A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFAF2)
val outlineDarkHighContrast = Color(0xFFCFCBB9)
val outlineVariantDarkHighContrast = Color(0xFFCFCBB9)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E2D5)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF2F2B00)
val surfaceDimDarkHighContrast = Color(0xFF15140C)
val surfaceBrightDarkHighContrast = Color(0xFF3B3930)
val surfaceContainerLowestDarkHighContrast = Color(0xFF0F0E07)
val surfaceContainerLowDarkHighContrast = Color(0xFF1D1C14)
val surfaceContainerDarkHighContrast = Color(0xFF212017)
val surfaceContainerHighDarkHighContrast = Color(0xFF2C2A21)
val surfaceContainerHighestDarkHighContrast = Color(0xFF37352C)

val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)